name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload files to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SSH_USERNAME }}
          server: ${{ secrets.SSH_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          local_path: './*'
          remote_path: ${{ secrets.REMOTE_TARGET }}
          sftp_only: true
